<?php

namespace ComisionRemuneradaBundle\Repository;

/**
 * SolicitudComisionServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudComisionServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
