<?php

namespace ConcursoOposicionBundle\Repository;

/**
 * ActaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActaRepository extends \Doctrine\ORM\EntityRepository
{
}
