<?php

namespace ConcursoOposicionBundle\Repository;

/**
 * AutorizadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutorizadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
