<?php

namespace ConcursoOposicionBundle\Repository;

/**
 * RecusacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecusacionRepository extends \Doctrine\ORM\EntityRepository
{
}
