<?php

namespace TramiteBundle\Repository;

/**
 * DuracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuracionRepository extends \Doctrine\ORM\EntityRepository
{
}
