clausulas_contractuales_prima_hijos:
    path:     /clausulas-contractuales/prima-hijos
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:primaHijos}
    requirements:
        _method:  POST

clausulas_contractuales_discapacidad:
    path:     /clausulas-contractuales/discapacidad
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:discapacidad}
    requirements:
        _method:  POST
    
clausulas_contractuales_beca:
    path:     /clausulas-contractuales/beca
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:beca}
    requirements:
        _method:  POST

clausulas_contractuales_consultar_beca:
    path:     /clausulas-contractuales/consultar-beca
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarBeca}

clausulas_contractuales_consultar_prima_hijos:
    path:     /clausulas-contractuales/consultar-prima-hijos
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarPrimaHijos}

clausulas_contractuales_consultar_discapacidad:
    path:     /clausulas-contractuales/consultar-discapacidad
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarDiscapacidad}

clausulas_contractuales_guardarArchivosBecaAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosBeca
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosBecaAjax}
    requirements:
        _method:  POST

clausulas_contractuales_guardarArchivosPrimaAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosPrima
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosPrimaAjax}
    requirements:
        _method:  POST

clausulas_contractuales_guardarArchivosDiscapacidadAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosDiscapacidad
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosDiscapacidadAjax}
    requirements:
        _method:  POST

clausulas_contractuales_discapacidadIndex:
    path:     /clausulas-contractuales/discapacidadIndex/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:discapacidadIndex}

clausulas_contractuales_indicador_de_reproceso_index:
    path:     /clausulas-contractuales/indicadorDeReprocesoIndex
    defaults: { _controller: ClausulasContractualesABundle:Reporte:indicadorDeReprocesoIndex}

clausulas_contractuales_rendicion_por_frecuencia_index:
    path:     /clausulas-contractuales/rendicionPorFrecuenciaIndex
    defaults: { _controller: ClausulasContractualesABundle:Reporte:rendicionPorFrecuenciaIndex}
    
clausulas_contractuales_rendicion_por_monto_index:
    path:     /clausulas-contractuales/rendicionPorMontoIndex
    defaults: { _controller: ClausulasContractualesABundle:Reporte:rendicionPorMontoIndex}

clausulas_contractuales_becaIndex:
    path:     /clausulas-contractuales/becaIndex/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:becaIndex}

clausulas_contractuales_prima_hijosIndex:
    path:     /clausulas-contractuales/primaHijosIndex/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:primaHijosIndex}

clausulas_contractuales_mantenimiento_de_montos:
    path:     /clausulas-contractuales/mantenimientoDeMontos
    defaults: { _controller: ClausulasContractualesABundle:MantenimientoMontos:mantenimientoDeMontosIndex}

clausulas_contractuales_mantenimiento_de_montos_enviar_data:
    path:     /clausulas-contractuales/mantenimientoDeMontosEnviarData
    defaults: { _controller: ClausulasContractualesABundle:MantenimientoMontos:mantenimientoDeMontosEnviarData}
    requirements:
        _method:  POST