clausulas_contractuales_prima_hijos:
    path:     /clausulas-contractuales/prima-hijos/{email}/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:primaHijos}
    
clausulas_contractuales_discapacidad:
    path:     /clausulas-contractuales/discapacidad/{email}/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:discapacidad}
    
clausulas_contractuales_beca:
    path:     /clausulas-contractuales/beca/{email}/{state}
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:beca}
    
clausulas_contractuales_consultar_beca:
    path:     /clausulas-contractuales/consultar-beca
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarBeca}
    
clausulas_contractuales_consultar_prima_hijos:
    path:     /clausulas-contractuales/consultar-prima-hijos
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarPrimaHijos}
    
clausulas_contractuales_consultar_discapacidad:
    path:     /clausulas-contractuales/consultar-discapacidad
    defaults: { _controller: ClausulasContractualesABundle:Consulta:consultarDiscapacidad}

clausulas_contractuales_guardarArchivosBecaAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosBeca
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosBecaAjax}
    requirements:
        _method:  POST

clausulas_contractuales_guardarArchivosPrimaAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosPrima
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosPrimaAjax}
    requirements:
        _method:  POST

clausulas_contractuales_guardarArchivosDiscapacidadAjaxAction:
    path:     /clausulas-contractuales/guardarArchivosDiscapacidad
    defaults: { _controller: ClausulasContractualesABundle:Solicitud:guardarArchivosDiscapacidadAjax}
    requirements:
        _method:  POST