descarga_horaria_homepage:
    path:     /descarga_horaria
    defaults: { _controller: DescargaHorariaBundle:Default:index }

descarga_horaria_informacion:
    path:     /descarga_horaria/info
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:info }
    
descarga_horaria_cargos_adm_univ:
    path:     /descarga_horaria/cargos
    defaults: { _controller: DescargaHorariaBundle:Cargos:consultarCargos }

descarga_horaria_solicitud:
    path:     /descarga_horaria/solicitud
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:solicitar }
    
descarga_horaria_generar_oficio_solicitud:
    path:     /descarga_horaria/generar-oficio-solicitud
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:generarOficioSolicitud }
    
descarga_horaria_nuevo_oficio:
    path:     /descarga_horaria/nuevo-oficio
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:oficioSolicitud }
    requirements:
        _method: POST|GET

descarga_horaria_informe_pdf:
    path:     /descarga_horaria/informe-pdf
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:informePDF }
    requirements:
        _method: GET
        
oficio_solicitud_data_ajax:
    path:     /descarga_horaria/oficio-solicitud-datos
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:oficioSolicitudData }
    requirements:
        _method:  POST

oficio_solicitud_buscarcedula_ajax:
    path:     /descarga_horaria/oficio-solicitud-buscar-cedula
    defaults: { _controller: DescargaHorariaBundle:SolicitarDescarga:buscarCedulaAjax }
    requirements:
        _method:  POST

registro_buscaremailconsultar_ajax:
    path:     /consulta/buscar-email-consulta-usuario
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:buscarEmailAjax }
    requirements:
        _method:  POST
    
