registro_usuario_index: 
    path:     /registro/usuario
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:registrarUsuario }

registro_registeruser_ajax:
    path:     /registro/registrar-usuario
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:registrarUsuarioAjax }
    requirements:
        _method:  POST
        
registro_buscarcedula_ajax:
    path:     /registro/buscar-cedula
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:buscarCedulaAjax }
    requirements:
        _method:  POST
        
registro_datos_index:
    path:     /registro/datos/{apr}
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:registrarDatosUsuario }

registro_guardar_ajax:
    path:     /registro/guardar-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:guardarDatosAjax }
    requirements:
        _method:  POST

registro_guardararchivos_ajax:
    path:     /registro/guardar-archivos-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:guardarArchivosAjax }
    requirements:
        _method:  POST
        
registro_obtener_ajax:
    path:     /registro/obtener-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:enviarDataAjax }
    requirements:
        _method:  POST
        
registro_buscaremail_ajax:
    path:     /registro/buscar-email
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:buscarEmailAjax }
    requirements:
        _method:  POST
        
registro_obteneremails_ajax:
    path:     /registro/enviar-emails
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:enviarEmailsAjax }
    requirements:
        _method:  POST

registro_obtenerlastid_ajax:
    path:    /registro/enviar-lastid
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:obtenerIdAjax }
    requirements:
        _method:  POST

registro_consulta_index:
    path:     /registro/consulta/{apr}
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:consultarRegistro }

registro_consultaobteneremails_ajax:
    path:     /consulta/enviar-emails
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarEmailsAjax }

registro_consultaobtenercedulas_ajax:
    path:     /consulta/enviar-cedulas
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarCedulasAjax }

registro_consultarregistros_ajax:
    path:     /consulta/enviar-registros
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeUsuarioAjax }

registro_consultarparticipantes_ajax:
    path:     /consulta/enviar-participantes
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeParticipantesAjax }

registro_consultarrevistas_ajax:
    path:     /consulta/enviar-revistas
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeRevistasAjax }

registro_consultardatospersonales_ajax:
    path:     /consulta/enviar-datos-personales
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesAjax }

registro_consultarcargos_ajax:
    path:     /consulta/enviar-cargos
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarCargosDeUsuarioAjax }

registro_consultarhijos_ajax:
    path:     /consulta/enviar-hijos
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesHijosAjax }

registro_consultardocumentshijos_ajax:
    path:     /consulta/enviar-hijos-url
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesHijosPathAjax }
    
registro_consultarbuscaremail_ajax:
    path:     /consulta/buscar-email
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:buscarEmailAjax }

registro_editardatos_ajax:
    path:     /consulta/editar-datos
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:editarDatosDeUsuario }
    requirements:
        _method:  POST
        
registro_consultarusuario_index:
    path:     /consulta/usuario
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:consultarUsuario }

registro_buscaremailconsultar_ajax:
    path:     /consulta/buscar-email-consulta-usuario
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:buscarEmailAjax }
    requirements:
        _method:  POST
registro_consultarusuario_ajax:
    path:     /consulta/obtener-datos-consulta-usuario
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:obtenerDatosDeUsuarioAjax }
    requirements:
        _method:  POST
registro_consultarroles_ajax:
    path:     /consulta/obtener-roles
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:obtenerRolesDeUsuarioAjax }
registro_buscarcedulaconsultar_ajax:
    path:     /consulta/obtener-cedula
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:buscarCedulaAjax }
    requirements:
        _method:  POST
registro_actualizarusuario_ajax:
    path:     /consulta/actualizar-usuario
    defaults: { _controller: RegistroUnicoBundle:ConsultarUsuario:actualizarDatosDeUsuario }
    requirements:
        _method:  POST
registro_guardararchivosconsulta_ajax:
    path:     /consulta/guardar-archivos-consulta/{email}/{execute}
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:guardarArchivos }
    requirements:
        _method:  POST

registro_validar_index: 
    path:     /validar/registro
    defaults: { _controller: RegistroUnicoBundle:ValidarRegistros:validarRegistros }

registro_validar_iframe_index: 
    path:     /validar/registro-iframe
    defaults: { _controller: RegistroUnicoBundle:ValidarRegistros:mostrarIframe }
    
registro_validarconsultarregistros_ajax:
    path:     /validar/enviar-registros
    defaults: { _controller: RegistroUnicoBundle:ValidarRegistros:enviarRegistros }
    requirements:
        _method:  POST
        
registro_validaractualizarregistros_ajax:
    path:     /validar/actualizar
    defaults: { _controller: RegistroUnicoBundle:ValidarRegistros:actualizarRegistros }
    requirements:
        _method:  POST

registro_eliminar_index:
    path:     /eliminar/registro
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:eliminarUsuarioIndex }
    
registro_eliminarconsultarusaurios_ajax:
    path:     /eliminar/enviar-usuarios
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:eliminarEnviarUsuario }
    requirements:
        _method:  POST
        
registro_eliminarusaurios_ajax:
    path:     /eliminar/eliminar-usuario
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:eliminarUsuario }
    requirements:
        _method:  POST
        
registro_activar_index:
    path:     /activar/registro
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:activarUsuarioIndex }
    
registro_activarconsultarusaurios_ajax:
    path:     /activar/enviar-usuarios
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:activarEnviarUsuario }
    requirements:
        _method:  POST
        
registro_activarusaurios_ajax:
    path:     /eliminar/activar-usuario
    defaults: { _controller: RegistroUnicoBundle:EliminarUsuario:activarUsuario }
    requirements:
        _method:  POST

registro_consultarbuscarcedula_ajax:
    path:     /consultar/buscar-cedula
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:buscarCedulaAjax }
    requirements:
        _method:  POST

registro_validaractualizararchivos_ajax:
    path:     /validar/actualizar-archivos
    defaults: { _controller: RegistroUnicoBundle:ValidarRegistros:validarArchivos }
    requirements:
        _method:  POST
