<?php

namespace TramiteBundle\Repository;

/**
 * MontoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MontoRepository extends \Doctrine\ORM\EntityRepository
{
}
