<?php

namespace AppBundle\Repository;

/**
 * PermisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisosRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPermisoNombresByUserCedula($cedula)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p.nombre FROM AppBundle\Entity\Usuario u
             JOIN u.roles r JOIN r.permisos p
             WHERE u.cedula = :cedula'
        );
        $query->setParameter('cedula', $cedula);

        return $query->getResult();
    }
}
