<?php

namespace AppBundle\Repository;

/**
 * PermisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisosRepository extends \Doctrine\ORM\EntityRepository
{
}
