<?php

namespace AppBundle\Repository;

/**
 * RecaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
