<?php

namespace AppBundle\Repository;

/**
 * Tipo_recaudoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Tipo_recaudoRepository extends \Doctrine\ORM\EntityRepository
{
}
