descarga_horaria:
    resource: "@DescargaHorariaBundle/Resources/config/routing.yml"
    prefix:   /

jubilacion_tramite_jubilacion:
    resource: "@JubilacionBundle/Controller/TramiteJubilacionController.php"
    type:     annotation

tramite_recaudo:
    resource: "@TramiteBundle/Controller/RecaudoController.php"
    type:     annotation

comision_remunerada_solicitud_comision_servicio:
    resource: "@ComisionRemuneradaBundle/Controller/SolicitudComisionServicioController.php"
    type:     annotation
    prefix:   /

concurso_oposicion:
    resource: "@ConcursoOposicionBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

concursos:
    resource: "@ConcursosBundle/Controller/"
    type:     annotation
    prefix:   /

reincorporacion:
    resource: "@ReincorporacionBundle/Controller/"
    type:     annotation
    prefix:   /

jubilacion:
    resource: "@JubilacionBundle/Controller/"
    type:     annotation
    prefix:   /

comision_remunerada:
    resource: "@ComisionRemuneradaBundle/Controller/"
    type:     annotation
    prefix:   /

clausulas_contractuales_b:
    resource: "@ClausulasContractualesBBundle/Resources/config/routing.yml"
    prefix:   /

clausulas_contractuales_a:
    resource: "@ClausulasContractualesABundle/Resources/config/routing.yml"
    prefix:   /

preparadores:
    resource: "@PreparadoresBundle/Controller/"
    type:     annotation
    prefix:   /

clausulas_contractuales:
    resource: "@ClausulasContractualesBundle/Resources/config/routing.yml"
    prefix:   /

registro_unico:
    resource: "@RegistroUnicoBundle/Resources/config/routing.yml"
    prefix:   /

plan_septenal:
    resource: "@PlanSeptenalBundle/Controller/"
    type:     annotation
    prefix:   /
