<?php

namespace ReincorporacionBundle\Repository;

/**
 * DesincorporacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DesincorporacionRepository extends \Doctrine\ORM\EntityRepository
{
}
