<?php

namespace ReincorporacionBundle\Repository;

/**
 * TramiteReincorporacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteReincorporacionRepository extends \Doctrine\ORM\EntityRepository
{
}
