<?php

namespace JubilacionBundle\Repository;

/**
 * TramiteJubilacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteJubilacionRepository extends \Doctrine\ORM\EntityRepository
{
}
