<?php

namespace DescargaHorariaBundle\Repository;

/**
 * CargoDesignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargoDesignacionRepository extends \Doctrine\ORM\EntityRepository
{
}
