<?php

namespace DescargaHorariaBundle\Repository;

/**
 * NombramientoCargoAdmUnivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NombramientoCargoAdmUnivRepository extends \Doctrine\ORM\EntityRepository
{
}
