<?php

namespace DescargaHorariaBundle\Repository;

/**
 * PlanAcademicoIntegralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanAcademicoIntegralRepository extends \Doctrine\ORM\EntityRepository
{
}
