<?php

namespace DescargaHorariaBundle\Repository;

/**
 * TipoDedicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDedicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
