<?php

namespace DescargaHorariaBundle\Repository;

/**
 * TipoPlanAcadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPlanAcadRepository extends \Doctrine\ORM\EntityRepository
{
}
