<?php

namespace ConcursosBundle\Repository;

/**
 * ConcursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcursoRepository extends \Doctrine\ORM\EntityRepository
{
}
