<?php

namespace ConcursosBundle\Repository;

/**
 * JuradoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuradoRepository extends \Doctrine\ORM\EntityRepository
{
}
