<?php

namespace RegistroUnicoBundle\Repository;

/**
 * EscuelaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscuelaRepository extends \Doctrine\ORM\EntityRepository
{
}
