<?php

namespace RegistroUnicoBundle\Repository;

/**
 * TipoRegistroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRegistroRepository extends \Doctrine\ORM\EntityRepository
{
}
