<?php

namespace RegistroUnicoBundle\Repository;

/**
 * UsuarioFechaCargoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioFechaCargoRepository extends \Doctrine\ORM\EntityRepository
{
}
